# Problem 1 

In [11]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array1=np.array([1,89,47,16,54])
print(array1)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
array2=np.sort(array1)
print(array2)











[ 1 89 47 16 54]
[ 1 16 47 54 89]


# Problem 2

In [58]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
x=np.array([10,15,30,45,60])
print(x)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
y=np.arange(5,15)
print(y)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
z=np.arange(50,100,5)
print(z)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
zero=np.zeros(10)
print(zero)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
one=np.ones(10)
print(one)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
l=np.linspace(0,100,6)
print(l)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
r=np.random.randint(10,30,5)
print(r)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
t=np.linspace(-1,1,9)
print(t)
u=np.random.uniform(-1,1,10)
print(u)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris1=np.random.randint(10,50,(3,5))
matris1_re=matris1.reshape(3,5)
print(f"Random Matris (3x5):\n{matris1_re}")

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
sutun = matris1_re.sum(axis = 1)
print(f"Sütun toplam: {sutun}")
satir = matris1_re.sum(axis = 0)
print(f"Satır toplam:{satir}")

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
max_deger = matris1_re.max()
min_deger = matris1_re.min()
ort_deger = matris1_re.mean()
print(f"Maximum değer:{max_deger}")
print(f"Minimum değer:{min_deger}")
print(f"Matris ortalaması: {ort_deger}")

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index=np.unravel_index(matris1_re.argmax(), matris1_re.shape)
print(f"Maximum değerin indexi: {max_index}")

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
a=np.arange(10,20)
print(a)
print(a[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(a[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(matris1_re[0,:])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(matris1_re[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matris1_re[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(matris1_re**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris_aralık=matris1_re[(matris1_re<50) & (matris1_re>-50)]
pozitif_cift=matris_aralık[(matris_aralık>0) & (matris_aralık%2==0)]
print(f"Aralıktaki pozitif çift sayılar: {pozitif_cift}")

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  20.  40.  60.  80. 100.]
[19 16 17 10 21]
[-1.   -0.75 -0.5  -0.25  0.    0.25  0.5   0.75  1.  ]
[-0.48031609  0.80645522 -0.58164426  0.2050121   0.10772396  0.04927209
 -0.38245828  0.02335138 -0.77853816 -0.16252746]
Random Matris (3x5):
[[36 13 28 48 36]
 [11 15 22 32 25]
 [43 34 23 34 29]]
Sütun toplam: [161 105 163]
Satır toplam:[ 90  62  73 114  90]
Maximum değer:48
Minimum değer:11
Matris ortalaması: 28.6
Maximum değerin indexi: (np.int64(0), np.int64(3))
[10 11 12 13 14 15 16 17 18 19]
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[36 13 28 48 36]
22
[36 11 43]
[[1296  169  784 2304 1296]
 [ 121  225  484 1024  625]
 [1849 1156  529 1156  841]]
Aralıktaki pozitif çift sayılar: [36 28 48 36 22 32 34 34]
