# Problem 1

In [14]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin

import numpy as np

a = np.random.randint(0,11,5)
print(a)

print(a.shape)

b = a.reshape(5,1)
print(b)

print(b.ndim)

[5 2 3 1 9]
(5,)
[[5]
 [2]
 [3]
 [1]
 [9]]
2


# Problem 2

In [25]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

# 2 - Oluşturduğunuz matrisi parçalayın

# 3 - Parçalanmış matrisleri birleştirin

q = np.arange(1,10,2)
print(q)

q1,q2=np.split(q,[3])
print(q1)
print(q2)

q_vol2=np.concatenate((q1,q2))
print(q_vol2)



[1 3 5 7 9]
[1 3 5]
[7 9]
[1 3 5 7 9]


# Problem 3

In [20]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

# 2 - matris'in özelliklerini inceleyin

x = np.arange(5,101,2)
y = np.random.choice(x,10)
print(y)

print(y.shape)
print(y.size)
print(y.dtype)


[53 41 57 19 21 87 29 39 15 89]
(10,)
10
int64
